//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicForNow.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Song
    {
        [Display(Name = "Song ID")]
        public string Song_ID { get; set; }
        [Display(Name = "Song Name")]
        public string Name { get; set; }
        public string Artist { get; set; }
        public string Album { get; set; }
        [Display(Name = "Release Date")]
        public Nullable<System.DateTime> ReleaseDate { get; set; }
        [Display(Name = "File")]
        public byte[] Song_File { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Album Album1 { get; set; }
        public virtual Artist Artist1 { get; set; }
    }
}
